### ISSUE TITLE
Open Error on big sample file

### ISSUE THREAD

**Issue by Taiwing** [sepich/thanos-kit#1]
I am trying to do some backfilling on a 6 months old database with thanos-kit. The fallowing command works with small samples,
but not with the entire metric history:

`thanos-kit import --label=test=data --input-file=testnet_metric_history --objstore.config='{ type: FILESYSTEM, config: { bucket: mybucket, directory: local_data }}'`

I get this output:

> level=info ts=2020-10-05T12:21:18.952642185Z caller=import.go:84 msg="cleanup cache dir"
> level=info ts=2020-10-05T12:21:18.952690304Z caller=import.go:41 msg="started importing input data."
> create tsdb blocks: add sample: new tsdb writer: tsdb.NewHead: open /tmp/head202214109/chunks_head: too many open files

I am guessing that because of the size of the sample thanos-kit tries to open more files than is allowed by the system.

**Comment by Taiwing** [comment]
By the way, if anyone is looking for a quick fix, you just have to divide your input sample file into multiple samples and import them one at a time.

**Comment by sepich** [comment]
Yes, that is known issue of current upstream import implementation. And the workaround is mentioned in the very bottom of [Readme](https://github.com/sepich/thanos-kit). Please suggest if it should have some other wording.
Another thing you can try is to bump open file limit with something like `docker run --ulimit nofile=90000:90000`

**Comment by Taiwing** [comment]
Ok, I didnt get it the first time as I am not very familiar with thanos terminology and it did not say it was gonna give an error. I thought it was unexpected.

**Comment by sepich** [comment]
It should work better now for big files.
Please reopen if there still issues
